# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install MAUI workload
      run: dotnet workload install maccatalyst maui-maccatalyst
      
    - name: Restore dependencies
      run: dotnet restore Electrify/Electrify.sln
      
    - name: Build
      run: dotnet build Electrify/Electrify.sln --no-restore
      
    - name: Test
      run: dotnet test Electrify/Electrify.sln -p:CollectCoverage=true -p:CoverletOutput=../TestResults/coverage -p:MergeWith=../TestResults/coverage.json -p:CoverletOutputFormat='json%2copencover' --no-build --verbosity normal
      
    - name: TempTest
      run: ls -R
      
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Test Coverage
        color: brightgreen
        path: TestResults/coverage.opencover.xml
        gist-filename: electrify-code-coverage.json
        gist-id: aa76ad223dfcd71c919610990ab72893
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}  
