name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI workload
      run: dotnet workload install maccatalyst maui-maccatalyst
    - name: Restore dependencies
      run: dotnet restore Electrify/Electrify.sln
    - name: Build
      run: dotnet build Electrify/Electrify.sln --no-restore

  unit-test:
    runs-on: macos-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI workload
      run: dotnet workload install maccatalyst maui-maccatalyst
    - name: Restore dependencies
      run: dotnet restore Electrify/Electrify.sln
    - name: UnitTest
      run: dotnet test Electrify/Electrify.UnitTests/Electrify.UnitTests.csproj --no-build --verbosity normal

  component-test:
    runs-on: macos-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI workload
      run: dotnet workload install maccatalyst maui-maccatalyst
    - name: Restore dependencies
      run: dotnet restore Electrify/Electrify.sln
    - name: ComponentTest
      run: dotnet test Electrify/Electrify.ComponentTests/Electrify.ComponentTests.csproj --no-build --verbosity normal
